spring.application.name=backend
spring.data.mongodb.uri=mongodb://localhost:27017/pi
server.port=8080
spring.servlet.multipart.max-file-size=6MB
spring.servlet.multipart.max-request-size=6MB
stripe.public.key=pk_test_51TPlyKLdfAtetbrBd8vl2u2H6uvfvXlzCiN1OtlCB1NGVs48916B1LbUMqA3uTPSliYhZFnOIanDY67nJhOFIQKb00xA89RyiG
stripe.success.url=http://localhost:4200/payment-success?session_id={CHECKOUT_SESSION_ID}
stripe.cancel.url=http://localhost:4200/payment-cancel
app.exchange.rate.tnd.eur=3.35
